### PR TITLE
Added features to abuse ManageCA and ManageCertificates permissions (ESC7)

### PR DESCRIPTION
**Pull request by Kudaes**
Two new commands have been added in order to replicate PSPKI functionalities to perform the ESC7 attack:

- setconfig: It allows to abuse ManageCA permission to both enable EDITF_ATTRIBUTESUBJECTALTNAME2 and to disable REQDISP_PENDINGFIRST. This command has an optional flag "/restart" to remotely restart the service CertSvc in order to apply the setting changes.

- issue: It allows to abuse ManageCertificates to issue an approval pending certificate.

### CODE REVIEW

**Comment by CaledoniaProject** [comment]
@Kudaes Which part of the code references the RSAT library?

**Comment by Kudaes** [comment]
@CaledoniaProject Mostly the functions added in the file ModifyConfigEntry.cs. Anywhere you see the use of the interface ICertAdmin2 means that we are using the DCOM functionality contained in the library certadm.dll. You could try to register manually this dll using regsvr32, but the only way that I've gotten it to work is by installing RSAT.

**Comment by Kudaes** [comment]
Hi @leechristensen, any updates regarding this PR?

**Comment by leechristensen** [comment]
Hey @Kudaes , sorry for the delayed response on this. For now, we're not going to include this due to the dependency on the RSAT tools. If you can think of a way to support Certify running while not having them installed on the machine, we'd be happy to include it.

Awesome research nonetheless and thanks for taking the time to make these contributions!

**Pull request closed without merging**
